docs: Update README and add GitHub action
bats-core/bats-detik pull request #36
Opened 2022-03-14 20:15 UTC by xakraz

2022-03-15 09:08 UTC, vincent-zurczak commented
Hello @xakraz

Thank you for this contribution. :)
BTW, I did not know about the Github TOC action.

I start a review.

2022-03-15 09:10 UTC, vincent-zurczak requested changes
Minor typos to fix.

2022-03-15 09:10 UTC, vincent-zurczak commented on README.md
> +
Why these two empty lines at the beginning?

2022-03-15 09:10 UTC, vincent-zurczak commented on README.md
> +> So, most of the time, you will want to verify the number of instances
To end with a dot.

2022-03-15 09:10 UTC, vincent-zurczak commented on README.md
> +Hence this additional syntax (Using [next section](#verifying-property-values) documentation to verify additionnal properties):
using (all in lower case)

2022-03-15 13:45 UTC, xakraz commented on README.md
> +
Just an oversight 😅 

By default, `doctoc` puts the TOC at the beginning of the file.
I moved it down to the location of the previous toc and did not notice these 2 empty lines.

Fixing

2022-03-15 13:47 UTC, xakraz commented on README.md
> +> So, most of the time, you will want to verify the number of instances
❓ The sentence continues the line after.
It seems to be a carriage return issue.

Fixing

2022-03-15 13:55 UTC, vincent-zurczak approved these changes

2022-03-15 13:58 UTC, vincent-zurczak commented
Thanks. I have approved the changes. :+1: 
One last thing that is necessary so that I can merge is about [signing your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits). I know it is a little bit annoying, but this is required for all the DETIK projects.

2022-03-15 18:06 UTC, xakraz commented
@vincent-zurczak I setup my GPG key on GitHub and signed my commit (squashed by the way). 
I hope it is ok now 😄

2022-03-16 07:03 UTC, merged

2022-03-16 07:04 UTC, vincent-zurczak commented
Thanks! :)